#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const { Pool, types } = require("pg");
require("dotenv").config();

// Keep textual values for date/time/numeric so the generated SQL preserves the
// original representation as much as possible.
types.setTypeParser(1082, (value) => value); // date
types.setTypeParser(1114, (value) => value); // timestamp without time zone
types.setTypeParser(1184, (value) => value); // timestamp with time zone
types.setTypeParser(1186, (value) => value); // interval
types.setTypeParser(1700, (value) => value); // numeric

const args = parseArgs(process.argv.slice(2));

if (args.help || args.h) {
  printHelp();
  process.exit(0);
}

const databaseUrl = process.env.DATABASE_URL;
if (!databaseUrl) {
  console.error("DATABASE_URL nao encontrada no ambiente.");
  process.exit(1);
}

const schema = sanitizeIdentifier(
  args.schema || process.env.SCHEMA_PADRAO || "nextcar",
  "schema",
);
const outputPath = path.resolve(
  process.cwd(),
  args.output || args.out || `${schema}-inserts.sql`,
);
const batchSize = Math.max(
  parseInt(args.batchSize || args.batch || "200", 10) || 200,
  1,
);
const includeTables = splitCsv(args.tables);
const excludeTables = new Set(splitCsv(args.exclude));
const appendCreateSchema = !isFalsey(args.createSchema);

const pool = new Pool({
  connectionString: databaseUrl,
  max: parseInt(process.env.DB_POOL_MAX || "3", 10),
  idleTimeoutMillis: parseInt(process.env.DB_IDLE_TIMEOUT_MS || "30000", 10),
  connectionTimeoutMillis: parseInt(
    process.env.DB_CONNECTION_TIMEOUT_MS || "15000",
    10,
  ),
  ssl: {
    rejectUnauthorized: false,
  },
});

(async () => {
  const client = await pool.connect();
  try {
    const tables = await listTables(client, schema);
    const selectedTables = tables.filter((table) => {
      if (includeTables.length > 0 && !includeTables.includes(table))
        return false;
      if (excludeTables.has(table)) return false;
      return true;
    });

    const orderedTables = await orderTables(client, schema, selectedTables);
    const lines = [];

    lines.push("-- Generated by scripts/export-inserts.js");
    lines.push(`-- Schema: ${schema}`);
    lines.push("-- Compatible with PostgreSQL 9.6");
    lines.push("BEGIN;");
    lines.push("SET client_min_messages = warning;");
    lines.push("SET standard_conforming_strings = on;");
    if (appendCreateSchema) {
      lines.push(`CREATE SCHEMA IF NOT EXISTS ${quoteIdent(schema)};`);
    }
    lines.push("");

    for (const tableName of orderedTables) {
      const columns = await listColumns(client, schema, tableName);
      if (!columns.length) continue;

      const pkColumns = await listPrimaryKeys(client, schema, tableName);
      const rows = await fetchRows(client, schema, tableName, pkColumns);

      lines.push(`-- Table: ${schema}.${tableName}`);
      lines.push(`-- Rows: ${rows.length}`);

      if (rows.length === 0) {
        lines.push("");
        continue;
      }

      const columnList = columns
        .map((column) => quoteIdent(column.column_name))
        .join(", ");
      const rowChunks = chunk(rows, batchSize);

      for (const chunkRows of rowChunks) {
        const valuesSql = chunkRows
          .map((row) => {
            const values = columns.map((column) =>
              formatValue(row[column.column_name], column),
            );
            return `(${values.join(", ")})`;
          })
          .join(",\n  ");

        lines.push(
          `INSERT INTO ${qualifiedName(schema, tableName)} (${columnList}) VALUES`,
        );
        lines.push(`  ${valuesSql};`);
      }

      const sequenceStatements = buildSequenceStatements(
        schema,
        tableName,
        columns,
      );
      if (sequenceStatements.length > 0) {
        lines.push("");
        lines.push(...sequenceStatements);
      }

      lines.push("");
    }

    lines.push("COMMIT;");

    fs.writeFileSync(outputPath, `${lines.join("\n")}\n`, "utf8");
    console.log(`Dump gerado em: ${outputPath}`);
    console.log(`Schema exportado: ${schema}`);
    console.log(`Tabelas exportadas: ${orderedTables.length}`);
  } catch (error) {
    console.error("Falha ao gerar o dump de inserts:", error.message);
    process.exitCode = 1;
  } finally {
    client.release();
    await pool.end();
  }
})();

function parseArgs(argv) {
  const result = {};

  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];

    if (token === "--help" || token === "-h") {
      result.help = true;
      continue;
    }

    if (!token.startsWith("--")) continue;

    const eqIndex = token.indexOf("=");
    if (eqIndex >= 0) {
      const key = token.slice(2, eqIndex);
      const value = token.slice(eqIndex + 1);
      result[key] = value;
      continue;
    }

    const key = token.slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith("--")) {
      result[key] = next;
      i += 1;
    } else {
      result[key] = true;
    }
  }

  return result;
}

function printHelp() {
  console.log(`
Usage:
  node scripts/export-inserts.js --schema=nextcar --output=./dump.sql

Options:
  --schema        Schema to export. Default: SCHEMA_PADRAO or nextcar
  --output        Output file path. Default: <schema>-inserts.sql
  --tables        Comma-separated list of tables to export
  --exclude       Comma-separated list of tables to skip
  --batch-size    Rows per INSERT statement. Default: 200
  --create-schema 1|0   Include CREATE SCHEMA IF NOT EXISTS. Default: 1
`);
}

function splitCsv(value) {
  if (!value) return [];
  return String(value)
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function isFalsey(value) {
  if (value === false) return true;
  if (value === 0) return true;
  if (value === "0") return true;
  if (value === "false") return true;
  if (value === "False") return true;
  if (value === "FALSE") return true;
  return false;
}

function sanitizeIdentifier(value, label) {
  const text = String(value || "").trim();
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(text)) {
    throw new Error(`${label} invalido: ${text}`);
  }
  return text;
}

function quoteIdent(value) {
  return '"' + String(value).replace(/"/g, '""') + '"';
}

function qualifiedName(schema, table) {
  return `${quoteIdent(schema)}.${quoteIdent(table)}`;
}

function escapeLiteral(value) {
  return `E'${String(value)
    .replace(/\\/g, "\\\\")
    .replace(/'/g, "''")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t")}'`;
}

function columnType(column) {
  return String(column.data_type || "").toLowerCase();
}

function columnUdt(column) {
  return String(column.udt_name || "").toLowerCase();
}

function isArrayColumn(column) {
  return columnType(column) === "array" || columnUdt(column).startsWith("_");
}

function arrayBaseType(column) {
  const udt = columnUdt(column);
  if (!udt.startsWith("_")) return "text";

  const base = udt.slice(1);
  const map = {
    int2: "smallint",
    int4: "integer",
    int8: "bigint",
    numeric: "numeric",
    float4: "real",
    float8: "double precision",
    bool: "boolean",
    text: "text",
    varchar: "varchar",
    bpchar: "char",
    uuid: "uuid",
    json: "json",
    jsonb: "jsonb",
    date: "date",
    timestamp: "timestamp",
    timestamptz: "timestamptz",
    time: "time",
    interval: "interval",
  };

  return map[base] || "text";
}

function formatArray(value, column) {
  const baseType = arrayBaseType(column);
  const items = Array.isArray(value) ? value : [];
  const formattedItems = items.map((item) =>
    formatScalar(item, { ...column, data_type: baseType, udt_name: baseType }),
  );
  return `ARRAY[${formattedItems.join(", ")}]::${baseType}[]`;
}

function formatJson(value, typeName) {
  const jsonText =
    value && typeof value === "object" ? JSON.stringify(value) : String(value);
  return `${escapeLiteral(jsonText)}::${typeName}`;
}

function formatScalar(value, column) {
  if (value === null || value === undefined) return "NULL";

  if (Buffer.isBuffer(value)) {
    return `E'\\x${value.toString("hex")}'::bytea`;
  }

  if (typeof value === "boolean") {
    return value ? "TRUE" : "FALSE";
  }

  if (typeof value === "bigint") {
    return value.toString();
  }

  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "NULL";
  }

  if (Array.isArray(value)) {
    return formatArray(value, column);
  }

  const typeName = columnType(column);
  const udt = columnUdt(column);
  const text = String(value);

  if (
    typeName === "json" ||
    typeName === "jsonb" ||
    udt === "json" ||
    udt === "jsonb"
  ) {
    try {
      return formatJson(
        typeof value === "string" ? JSON.parse(value) : value,
        typeName === "json" || udt === "json" ? "json" : "jsonb",
      );
    } catch {
      return formatJson(
        text,
        typeName === "json" || udt === "json" ? "json" : "jsonb",
      );
    }
  }

  if (typeName === "date" || udt === "date") {
    return `${escapeLiteral(text)}::date`;
  }

  if (typeName === "timestamp without time zone" || udt === "timestamp") {
    return `${escapeLiteral(text)}::timestamp`;
  }

  if (typeName === "timestamp with time zone" || udt === "timestamptz") {
    return `${escapeLiteral(text)}::timestamptz`;
  }

  if (typeName === "time without time zone" || udt === "time") {
    return `${escapeLiteral(text)}::time`;
  }

  if (typeName === "interval" || udt === "interval") {
    return `${escapeLiteral(text)}::interval`;
  }

  if (
    typeName === "integer" ||
    typeName === "smallint" ||
    typeName === "bigint" ||
    typeName === "numeric" ||
    typeName === "real" ||
    typeName === "double precision" ||
    /^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/.test(text.trim())
  ) {
    return text;
  }

  if (typeName === "boolean") {
    const normalized = text.trim().toLowerCase();
    return ["t", "true", "1", "y", "yes"].includes(normalized)
      ? "TRUE"
      : "FALSE";
  }

  return escapeLiteral(text);
}

function formatValue(value, column) {
  if (isArrayColumn(column)) {
    return formatArray(value, column);
  }

  return formatScalar(value, column);
}

async function listTables(client, schema) {
  const result = await client.query(
    `
      SELECT table_name
      FROM information_schema.tables
      WHERE table_schema = $1
        AND table_type = 'BASE TABLE'
      ORDER BY table_name ASC
    `,
    [schema],
  );

  return result.rows.map((row) => row.table_name);
}

async function listColumns(client, schema, table) {
  const result = await client.query(
    `
      SELECT
        column_name,
        data_type,
        udt_name,
        ordinal_position,
        column_default,
        pg_get_serial_sequence($1 || '.' || $2, column_name) AS serial_sequence
      FROM information_schema.columns
      WHERE table_schema = $1
        AND table_name = $2
      ORDER BY ordinal_position ASC
    `,
    [schema, table],
  );

  return result.rows;
}

async function listPrimaryKeys(client, schema, table) {
  const result = await client.query(
    `
      SELECT a.attname AS column_name
      FROM pg_index i
      JOIN pg_class c ON c.oid = i.indrelid
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = ANY(i.indkey)
      WHERE n.nspname = $1
        AND c.relname = $2
        AND i.indisprimary
      ORDER BY a.attnum ASC
    `,
    [schema, table],
  );

  return result.rows.map((row) => row.column_name);
}

async function fetchRows(client, schema, table, primaryKeys) {
  const orderBy =
    primaryKeys.length > 0
      ? ` ORDER BY ${primaryKeys.map((column) => quoteIdent(column)).join(", ")}`
      : "";

  const result = await client.query(
    `SELECT * FROM ${qualifiedName(schema, table)}${orderBy}`,
  );
  return result.rows;
}

async function orderTables(client, schema, tables) {
  if (tables.length <= 1) return tables;

  const result = await client.query(
    `
      SELECT DISTINCT
        tc.table_name AS table_name,
        ccu.table_name AS referenced_table_name
      FROM information_schema.table_constraints tc
      JOIN information_schema.key_column_usage kcu
        ON tc.constraint_name = kcu.constraint_name
       AND tc.table_schema = kcu.table_schema
      JOIN information_schema.constraint_column_usage ccu
        ON ccu.constraint_name = tc.constraint_name
       AND ccu.constraint_schema = tc.table_schema
      WHERE tc.constraint_type = 'FOREIGN KEY'
        AND tc.table_schema = $1
    `,
    [schema],
  );

  const tableSet = new Set(tables);
  const graph = new Map();
  const incoming = new Map();

  for (const table of tables) {
    graph.set(table, new Set());
    incoming.set(table, 0);
  }

  for (const row of result.rows) {
    const from = row.table_name;
    const to = row.referenced_table_name;

    if (!tableSet.has(from) || !tableSet.has(to) || from === to) {
      continue;
    }

    if (!graph.get(to).has(from)) {
      graph.get(to).add(from);
      incoming.set(from, incoming.get(from) + 1);
    }
  }

  const queue = tables.filter((table) => incoming.get(table) === 0).sort();
  const ordered = [];

  while (queue.length > 0) {
    const current = queue.shift();
    ordered.push(current);

    for (const next of graph.get(current) || []) {
      incoming.set(next, incoming.get(next) - 1);
      if (incoming.get(next) === 0) {
        queue.push(next);
        queue.sort();
      }
    }
  }

  const remaining = tables.filter((table) => !ordered.includes(table)).sort();
  if (remaining.length > 0) {
    console.warn(
      `Aviso: dependencias ciclicas ou nao resolvidas em ${remaining.join(", ")}.`,
    );
    return [...ordered, ...remaining];
  }

  return ordered;
}

function buildSequenceStatements(schema, table, columns) {
  const statements = [];
  const tableName = qualifiedName(schema, table);

  for (const column of columns) {
    if (!column.serial_sequence) continue;

    statements.push(
      `SELECT setval(${escapeLiteral(column.serial_sequence)}, COALESCE((SELECT MAX(${quoteIdent(column.column_name)}) FROM ${tableName}), 1), (SELECT COUNT(*) > 0 FROM ${tableName})); -- ${tableName}.${quoteIdent(column.column_name)}`,
    );
  }

  return statements;
}

function chunk(items, size) {
  const chunks = [];
  for (let index = 0; index < items.length; index += size) {
    chunks.push(items.slice(index, index + size));
  }
  return chunks;
}
