name: Wake Koyeb App

on:
  schedule:
   - cron: "*/10 11-21 * * 1-5"
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar healthz
        run: |
          curl -fsS https://ytterbic-anita-nextcar-7681c717.koyeb.app/healthz
