name: Wake Koyeb App

on:
  schedule:
    # 08:00 até 20:50 BRT = 11:00 até 23:50 UTC
    - cron: "*/10 11-23 * * *"

    # 21:00 até 22:50 BRT = 00:00 até 01:50 UTC do dia seguinte
    - cron: "*/10 0-1 * * *"

  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest
    steps:
      - name: Chamar healthz
        run: |
          curl -fsS https://ytterbic-anita-nextcar-7681c717.koyeb.app/healthz
